// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUj7mLD0TAI8bY_blfsY_QfhuMIzS-Sbo',
    appId: '1:723145655461:web:b6901a11f8e8594a24794c',
    messagingSenderId: '723145655461',
    projectId: 'login-e7e60',
    authDomain: 'login-e7e60.firebaseapp.com',
    storageBucket: 'login-e7e60.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB41bjSuyVbqIYDOuE5Uw_S9JIMzHEs-0g',
    appId: '1:723145655461:android:3603db2e9bb72c7524794c',
    messagingSenderId: '723145655461',
    projectId: 'login-e7e60',
    storageBucket: 'login-e7e60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvo2kinU-zexgrhaDKVCCw0-vY4yZZWpw',
    appId: '1:723145655461:ios:2887e3e95462e99c24794c',
    messagingSenderId: '723145655461',
    projectId: 'login-e7e60',
    storageBucket: 'login-e7e60.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvo2kinU-zexgrhaDKVCCw0-vY4yZZWpw',
    appId: '1:723145655461:ios:2887e3e95462e99c24794c',
    messagingSenderId: '723145655461',
    projectId: 'login-e7e60',
    storageBucket: 'login-e7e60.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUj7mLD0TAI8bY_blfsY_QfhuMIzS-Sbo',
    appId: '1:723145655461:web:ca03d525c83450cb24794c',
    messagingSenderId: '723145655461',
    projectId: 'login-e7e60',
    authDomain: 'login-e7e60.firebaseapp.com',
    storageBucket: 'login-e7e60.firebasestorage.app',
  );
}
